# Generated by Django 3.2 on 2021-04-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_auto_20210420_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='emballag',
        ),
        migrations.DeleteModel(
            name='Emballage',
        ),
    ]
