# Generated by Django 3.2 on 2021-04-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_auto_20210421_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emballage',
            name='couleur',
            field=models.CharField(choices=[('bl', 'blanc'), ('rg', 'rouge'), ('ble', 'bleue'), ('vr', 'vert'), ('multi', 'multicolore'), ('trans', 'transparent')], default='Transparent', max_length=10),
        ),
    ]
