# Generated by Django 3.2 on 2021-05-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0013_alter_produit_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
